### PR TITLE
Reservoir MODMS-87

### PR DESCRIPTION
**Pull request by adamdickmeiss**
SonarQube fails as project is not configure there yet.

This PR will *not* be merged to master. Instead it will be the baseline (master) of a new mod-reservoir GitHub Project.

### CODE REVIEW

**Review by dcrossleyau — APPROVED** [review]
I did local search for the obvious old names. Okay.

There is one that i wonder about. In each POM `org.folio.meta.storage.xxx`, e.g.
```
<Automatic-Module-Name>org.folio.meta.storage.client</Automatic-Module-Name>
```

And i presume that the link to Jira will be a later change.

**Comment by adamdickmeiss** [comment]
> 



> I did local search for the obvious old names. Okay.
> 
> There is one that i wonder about. In each POM `org.folio.meta.storage.xxx`, e.g.
> 
> ```
> <Automatic-Module-Name>org.folio.meta.storage.client</Automatic-Module-Name>
> ```
> 
> And i presume that the link to Jira will be a later change.

good spot. Will fix. It worries me a bit that the build process did not fail because of this. Oh well.

**Comment by skoczko** [comment]
@dcrossleyau can the new repo be called simply "reservoir" rather than "mod-reservoir" or is there some hard-coded knowledge in the CI that expects the mod-prefix in the repo name?

**Comment by dcrossleyau** [comment]
There are various aspects of the infrastructure that expect `mod-` and `ui-` prefix, etc.

**Comment by adamdickmeiss** [comment]
Closed as PR is part of mod-reservoir.

**Pull request closed without merging**
