### PR TITLE
PMH client "all" for start/stop/status

### PR DESCRIPTION
**Pull request by adamdickmeiss**

### CODE REVIEW

**Comment by skoczko** [comment]
@adamdickmeiss How do you prevent clients with ID "all" from being created?

**Comment by adamdickmeiss** [comment]
> @adamdickmeiss How do you prevent clients with ID "all" from being created?

Don't. Will do!

**Comment by skoczko** [comment]
> > @adamdickmeiss How do you prevent clients with ID "all" from being created?
> 
> Don't. Will do!

Ok, it would make sense to have the syntax for "all" standout a little and use e.g `_all`

**Review by skoczko — CHANGES_REQUESTED** [review]
Switch to `_all`, prevent it from being used as and ID

**Review by skoczko — APPROVED** [review]

**Comment by skoczko** [comment]
@adamdickmeiss there are test failures it seems

**Pull request merged**
