### PR TITLE
Bump date by 1 when current date > 1 MODMS-72

### PR DESCRIPTION
**Pull request by skoczko**

### CODE REVIEW

**Review by adamdickmeiss — COMMENTED** [review]
Don't see the new code covered in tests. It could be tested by moving the snippet out to a method and test that

**Review by dcrossleyau — APPROVED** [review]

**Review by adamdickmeiss — COMMENTED** [review]
Why HOURS and not SECONDS for a server where the bump is seconds?

**Comment by skoczko** [comment]
@adamdickmeiss It's the safer option. With SECONDS it's just more likely that we would miss records. Remember that this is a heuristic and one that depends on the fact that our clock and server's clock is correct. In theory, it doesn't matter but in practice it's an additional protection when we hit the sever at exactly at the time were new records are being loaded into it.

**Comment by skoczko** [comment]
@adamdickmeiss is it okay I go ahead and merge? I'd like David to take it for a spin before EOW.

**Comment by adamdickmeiss** [comment]
> @adamdickmeiss It's the safer option. With SECONDS it's just more likely that we would miss records. Remember that this is a heuristic and one that depends on the fact that our clock and server's clock is correct. In theory, it doesn't matter but in practice it's an additional protection when we hit the sever at exactly at the time were new records are being loaded into it.

Ok

**Pull request merged**
